// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBR_2tClDsUY8HzXCUEL3Lmp3D5sZfDY',
    appId: '1:603514226899:web:2d9dad9158ee5ea4c0ac26',
    messagingSenderId: '603514226899',
    projectId: 'music-app-51c67',
    authDomain: 'music-app-51c67.firebaseapp.com',
    storageBucket: 'music-app-51c67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACa-J5ACgipI6vwe1yuekv571L9W2ysx4',
    appId: '1:603514226899:android:599b458fd2c91699c0ac26',
    messagingSenderId: '603514226899',
    projectId: 'music-app-51c67',
    storageBucket: 'music-app-51c67.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcx2NqvwE4QSBv1OG4qzUO-bIyyhzfyM',
    appId: '1:603514226899:ios:9553cfbc7ae06cacc0ac26',
    messagingSenderId: '603514226899',
    projectId: 'music-app-51c67',
    storageBucket: 'music-app-51c67.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcx2NqvwE4QSBv1OG4qzUO-bIyyhzfyM',
    appId: '1:603514226899:ios:9553cfbc7ae06cacc0ac26',
    messagingSenderId: '603514226899',
    projectId: 'music-app-51c67',
    storageBucket: 'music-app-51c67.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBR_2tClDsUY8HzXCUEL3Lmp3D5sZfDY',
    appId: '1:603514226899:web:eabc2a8e9b7b367ac0ac26',
    messagingSenderId: '603514226899',
    projectId: 'music-app-51c67',
    authDomain: 'music-app-51c67.firebaseapp.com',
    storageBucket: 'music-app-51c67.firebasestorage.app',
  );
}
